server:
  port: 8888
cors:
  originPatterns: http://localhost:8080,https://willyanferdinando.dev.br, http://localhost:3000
file:
  upload-dir: /home/willyan/workspace/cursos/rest-with-spring-boot-and-java/21_DOWNLOAD_UPLOAD/uploadDir
spring:
  application:
    name: rest-with-spring-boot-and-java
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB 
logging:
  level:
    # root: INFO
    '[br.com.wfsystems]': DEBUG
springdoc:
  paths-to-match: /api/**/v1/**
  swagger-ui:
    use-root-path: true
