name: Continuous Integration and Delivery with Github Actions

on:
  push:
    branches: 
      - "main" 
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
     
    - name: Setup Java 21     
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt'
        cache: 'maven'
        
    
    - name: Build Application .jar
      working-directory: ./28_DOKCER_APPLICATION/rest-with-spring-boot-and-java
      run: mvn clean package -DskipTests
      timeout-minutes: 20
    
    - name: Run Integration Tests
      working-directory: ./28_DOKCER_APPLICATION/rest-with-spring-boot-and-java
      run: mvn test -X
      timeout-minutes: 30
    
    - name: Docker Compose Build
      working-directory: ./28_DOKCER_APPLICATION/
      run: docker compose build
      timeout-minutes: 15
    
    - name: Push to Docker Hub Container Registry
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot-wfsystems:latest  ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot-wfsystems:${{ github.run_id }}
      
        docker push ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot-wfsystems:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot-wfsystems:${{ github.run_id }}